### PR TITLE
Lesjaw patch 1

### PR DESCRIPTION
**Pull request by lesjaw**

### CODE REVIEW

**Comment by plinioseniore** [comment]
Hi Les, 

the following action are required before proceed with the merge:
1) Remove the [Souliss Device Pushbullet Notification](https://github.com/lesjaw/souliss.github.io-lesjaw/blob/lesjaw-patch-1/Souliss%20Device%20Pushbullet%20Notification) from the root
2) Move the tutorial from tutorial/2015-07-26-SoulissPushbullet.md to _post/media/ folder.
3) In _post/media folder there is a template, use the first row of the template to assign the teaser picture, the author and others properties of the tutorial.
4) For code use ```C code ``` this will highlight C sintax and not general code sintax.
5) Insert at the end of the tutorial the whole sketch
6) Specify that this code will work with W5100 based Ethernet shield or devices and ESP8266.

Thanks for your tutorial,
Dario.

**Comment by lesjaw** [comment]
i can't understand step 4, how to insert C code, i write C code in the bottom, but the preview is so mess only some syntax got right format..

**Comment by plinioseniore** [comment]
Add C after ``` so that you can have ```C

**Comment by lesjaw** [comment]
Ok done..

**Comment by plinioseniore** [comment]
The tutorial is online at the following address, please note that I've changed the code to push the output state instead of the input state of the digital input. I kindly ask you to review it and let me know if this code is working properly.

I've done also some changes on the tutorial, adding a primary image and changing the code highlight because the template that we are using doesn't follow Mardown completely.

http://souliss.github.io/media/Souliss-ThingSpeaks-Pushbullet/

Let me know,
Dario.

**Comment by lesjaw** [comment]
Ok..nice juan.. i will test the code.. but in teory it should work.. it
seems much better..

will report asap..

**Pull request merged**
