### PR TITLE
added RPi2 fresh installation of OH + Souliss Binding

### PR DESCRIPTION
**Pull request by ribico**

### CODE REVIEW

**Comment by plinioseniore** [comment]
Great, it just miss a feature image 1600 pixels that will appear on top. Please move also the images fr github cloud to the images/2015-09 folder.

If the feature image has credits, use the credit option in the header to embed a link.

Thanks.

**Comment by ribico** [comment]
Added teaser and feature imgs now..
I don't undrestand how to use images in the folder, when I upload them to my fork links does not work (of course) because they refer to the souliss.github.io address

**Comment by plinioseniore** [comment]
Merged. Yep you cannot see them on your fork due to this path problem, I think that there isn't a solution.

**Comment by plinioseniore** [comment]
Please consider to add few lines on how to configure the binding for Souliss, referencing to the wiki.

Thanks.

**Comment by ribico** [comment]
OK I will.
Il 09/set/2015 10:19 AM, "Dario Di Maio" <notifications@github.com> ha
scritto:

**Pull request merged**
