### PR TITLE
Tutorial Using Eclipse Arduino IDE

### PR DESCRIPTION
**Pull request by dgolda**

### CODE REVIEW

**Comment by plinioseniore** [comment]
Can you please select or add images for the main picture and the teaser?

Main Picture : PNG, JPG 1600x800 pixel
Teaser : PNG, JPG 400x250 pixel

**Comment by dgolda** [comment]
Hmm, I'm not sure how.
Could you help?
[deleted]

**Comment by plinioseniore** [comment]
Is this image free from copyrights or has copyleft?

**Comment by dgolda** [comment]
You're right, it may be protected...

**Comment by dgolda** [comment]
What do you think about screenshots?
main
teaser

**Comment by plinioseniore** [comment]
Your tutorial is online here http://souliss.net/media/Using-Eclipse-Arduino-IDE/

Feel free to change your settings in [author](https://github.com/souliss/souliss.github.io/blob/master/_data/authors.yml) page.

**Pull request merged**
